<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <TargetZone>LocalIntranet</TargetZone>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>false</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Ximian_openofficecalc_Ximian_9948.ico</ApplicationIcon>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Gastos.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Gastos.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Ximian_openofficecalc_Ximian_9948.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Frm*.cs" />
    <Compile Remove="Program.cs" />
    <Compile Remove="ValidarNumero.cs" />
    <EmbeddedResource Remove="Frm*.resx" />
  </ItemGroup>
  <ItemGroup>
    <SupportedPlatform Include="Windows" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
